"""Cluster OOF mistakes and emit a falsifiable next-experiment suggestion."""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

from s6e8.contracts import NUMERIC_COLUMNS, SLICE_COLUMNS
from s6e8.metrics import hard_band_mask, missingness_cohorts, safe_roc_auc, slice_metrics

RESIDUAL_DEAD_THRESHOLD = 0.52


def _univariate_residual_auc(frame: pd.DataFrame, residual: np.ndarray) -> dict[str, float]:
    """AUC of |residual| ranking vs whether the row is in the hard band is not the goal.

    Here: can a raw column rank the *signed* residual? If AUC≈0.5, the column
    does not explain remaining errors.
    """
    y_sign = (residual > 0).astype(int)
    out: dict[str, float] = {}
    if y_sign.min() == y_sign.max():
        return out
    for col in NUMERIC_COLUMNS:
        if col not in frame.columns:
            continue
        s = frame[col]
        mask = s.notna()
        if int(mask.sum()) < 50 or np.unique(y_sign[mask.to_numpy()]).size < 2:
            continue
        try:
            raw = float(roc_auc_score(y_sign[mask.to_numpy()], s[mask].astype(float)))
        except ValueError:
            continue
        out[col] = max(raw, 1.0 - raw)
    return out


def analyze_oof_errors(
    frame: pd.DataFrame,
    y: np.ndarray,
    pred: np.ndarray,
    *,
    experiment: str = "unknown",
) -> dict[str, Any]:
    y_np = np.asarray(y)
    p = np.asarray(pred, dtype=float)
    residual = y_np - p
    slices = slice_metrics(y_np, p, frame, min_n=30)
    band = hard_band_mask(p)
    residual_auc = _univariate_residual_auc(frame.loc[band] if band.any() else frame, residual[band] if band.any() else residual)
    max_residual_auc = max(residual_auc.values()) if residual_auc else None

    hard_auc = slices.get("hard_band", {}).get("auc")
    suggestion: dict[str, Any]
    if max_residual_auc is not None and max_residual_auc >= RESIDUAL_DEAD_THRESHOLD + 0.03:
        best_col = max(residual_auc, key=residual_auc.get)  # type: ignore[arg-type]
        suggestion = {
            "action": "experiment",
            "primary_variable": "features",
            "hypothesis": (
                f"Hard-band residual still ranks on {best_col} "
                f"(AUC {residual_auc[best_col]:.3f}). Add an interaction or bin on that column."
            ),
            "suggested_config_stem": f"{experiment}_hardband_{best_col}",
            "engineering": {"add_interactions": True},
        }
    elif hard_auc is not None and hard_auc < 0.70:
        suggestion = {
            "action": "stop_or_ensemble",
            "primary_variable": "model_family",
            "hypothesis": (
                f"Hard-band OOF AUC is {hard_auc:.3f} and no raw column ranks the residual "
                f"(max {max_residual_auc}). Remaining errors look like generator noise; "
                "prefer a diverse tree family blend over new arithmetic features."
            ),
            "suggested_config_stem": None,
            "engineering": {},
        }
    else:
        suggestion = {
            "action": "stop",
            "primary_variable": None,
            "hypothesis": "No high-value error cluster remains in the OOF hard band.",
            "suggested_config_stem": None,
            "engineering": {},
        }

    cohort = missingness_cohorts(frame)
    return {
        "experiment": experiment,
        "oof_auc": safe_roc_auc(y_np, p),
        "slices": slices,
        "hard_band_n": int(band.sum()),
        "hard_band_auc": hard_auc,
        "residual_column_auc_in_hard_band": residual_auc,
        "max_residual_column_auc": max_residual_auc,
        "missingness_counts": cohort.value_counts().to_dict(),
        "cat_rate_spreads": {
            col: (
                float(frame.loc[y_np == 1, col].value_counts(normalize=True, dropna=False).max())
                - float(frame.loc[y_np == 0, col].value_counts(normalize=True, dropna=False).max())
                if col in frame.columns
                else None
            )
            for col in SLICE_COLUMNS
        },
        "suggestion": suggestion,
    }


def render_next_experiment_yaml(
    analysis: dict[str, Any],
    *,
    base_config_name: str = "lgbm_nocat",
) -> str | None:
    suggestion = analysis.get("suggestion") or {}
    stem = suggestion.get("suggested_config_stem")
    if not stem:
        return None
    hypothesis = suggestion.get("hypothesis", "")
    return f"""experiment:
  name: {stem}
  seed: 42
  data_version: v1
  feature_version: error_analysis_v1
  model_version: lgbm_v1
  hypothesis: >
    {hypothesis}
  change: Generated by scripts/error_analysis.py from {analysis.get("experiment")} OOF.
  expected_effect: Small OOF AUC lift on the hard-probability band, else stop.

# Copy missing blocks from configs/{base_config_name}.yaml before running.
# Primary variable: {suggestion.get("primary_variable")}
"""
